# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"model_predict": "01_Regression.ipynb",
         "combined_metrics": "01_Regression.ipynb",
         "confusion_matrix_plot": "01_Regression.ipynb",
         "to_excel": "01_Regression.ipynb",
         "get_table_download_link": "01_Regression.ipynb",
         "GNB": "01_Regression.ipynb",
         "LogisticReg": "01_Regression.ipynb",
         "KNN": "01_Regression.ipynb",
         "SVM": "01_Regression.ipynb",
         "DT": "01_Regression.ipynb",
         "RF": "01_Regression.ipynb",
         "GB": "01_Regression.ipynb",
         "ERT": "01_Regression.ipynb",
         "XGB": "01_Regression.ipynb",
         "SGD": "01_Regression.ipynb",
         "NN": "01_Regression.ipynb",
         "data": "01_Regression.ipynb",
         "test_data": "01_Regression.ipynb",
         "LinearReg": "01_Regression.ipynb"}

modules = ["core.py"]

doc_url = "https://jatin.github.io/autoML/"

git_url = "https://github.com/jatin/autoML/tree/master/"

def custom_doc_links(name): return None
