# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"model_predict": "00_Classification.ipynb",
         "combined_metrics": "00_Classification.ipynb",
         "confusion_matrix_plot": "00_Classification.ipynb",
         "to_excel": "00_Classification.ipynb",
         "get_table_download_link": "00_Classification.ipynb",
         "GNB": "00_Classification.ipynb",
         "LogisticReg": "00_Classification.ipynb",
         "KNN": "00_Classification.ipynb",
         "SVM": "00_Classification.ipynb",
         "DT": "00_Classification.ipynb",
         "RF": "00_Classification.ipynb",
         "GB": "00_Classification.ipynb",
         "ERT": "00_Classification.ipynb",
         "XGB": "00_Classification.ipynb",
         "SGD": "00_Classification.ipynb",
         "NN": "00_Classification.ipynb",
         "data": "00_Classification.ipynb",
         "test_data": "00_Classification.ipynb"}

modules = ["core.py"]

doc_url = "https://{jatin}.github.io/{autoML}/"

git_url = "https://github.com/{jatin}/{autoML}/tree/{master}/"

def custom_doc_links(name): return None
